dbt_northwind:
  outputs:
    dev:
      dbname: "{{ env_var('DBNAME_DBT') }}"
      host: "{{ env_var('HOST_DBT') }}"
      pass: "{{ env_var('PASSWORD_DBT') }}"
      port: "{{ env_var('PORT_DBT') | int }}"
      schema: "{{ env_var('SCHEMA_DBT') }}"
      threads: 1
      type: "{{ env_var('TYPE_DBT') }}"
      user: "{{ env_var('USER_DBT') }}"
  target: dev
