name: Deploy dbt docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dbt
      run: pip install dbt-postgres

    - name: Set up dbt profile
      run: |
        mkdir -p ~/.dbt
        echo "
        northwind:
          target: prod
          outputs:
            prod:
              type: postgres
              host: ${{ secrets.HOST_DBT }}
              port: ${{ secrets.PORT_DBT }}
              user: ${{ secrets.USER_DBT }}
              password: ${{ secrets.PASSWORD_DBT }}
              dbname: ${{ secrets.DBNAME_DBT }}
              schema: ${{ secrets.SCHEMA_DBT }}
              threads: 1
        " > ~/.dbt/profiles.yml

    - name: Install dependencies and generate docs
      run: |
        cd dbt_northwind
        dbt docs generate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAT }}
        publish_dir: ./northwind/target